=== libov/zeus/db/binning.dtd
<!ELEMENT binning (bin, bin_group)>
<!ELEMENT bin_group (bin)>
<!ELEMENT bin (subbin, k_uds, k_c, k_b, k_uds_err, k_c_err, k_b_err, sigma_uds_true, sigma_c_true, sigma_b_true, sigma_uds, sigma_c, sigma_b, sigma_uds_err, sigma_c_err, sigma_b_err, sigma_c_err_syst, sigma_b_err_syst)>
<!ELEMENT subbin (variable, low_edge, up_edge)>
<!ELEMENT variable (#PCDATA)>
<!ELEMENT low_edge (#PCDATA)>
<!ELEMENT up_edge (#PCDATA)>
<!ELEMENT k_uds (#PCDATA)>
<!ELEMENT k_c (#PCDATA)>
<!ELEMENT k_b (#PCDATA)>
<!ELEMENT k_uds_err (#PCDATA)>
<!ELEMENT k_c_err (#PCDATA)>
<!ELEMENT k_b_err (#PCDATA)>
<!ELEMENT sigma_uds_true (#PCDATA)>
<!ELEMENT sigma_c_true (#PCDATA)>
<!ELEMENT sigma_b_true (#PCDATA)>
<!ELEMENT sigma_uds (#PCDATA)>
<!ELEMENT sigma_c (#PCDATA)>
<!ELEMENT sigma_b (#PCDATA)>
<!ELEMENT sigma_uds_err (#PCDATA)>
<!ELEMENT sigma_c_err (#PCDATA)>
<!ELEMENT sigma_b_err (#PCDATA)>
<!ELEMENT sigma_c_err_syst (#PCDATA)>
<!ELEMENT sigma_b_err_syst (#PCDATA)>

=== libov/zeus/db/results.inclusive2.21.20.0405e06e07p.v02.true05e06e0607p.xml
<?xml version="1.0" encoding="UTF-8" standalone="no" ?><!DOCTYPE dataset SYSTEM "binning.dtd"><?xml-stylesheet type="text/xsl" href="binning.xsl"?><binning>
        <!-- eta jet -->
        <bin id="1" type="inlcusive">
                <subbin>
                        <variable>etajet</variable>
                        <low_edge>0</low_edge>
                        <up_edge>1</up_edge>
                </subbin>
                <k_uds>0.918207</k_uds>
                <k_c>1.23014</k_c>
                <k_b>1.45179</k_b>
                <k_uds_err>0.00468141</k_uds_err>
                <k_c_err>0.01933</k_c_err>
                <k_b_err>0.0532972</k_b_err>
                <sigma_uds_true>0</sigma_uds_true>
                <sigma_c_true>14015.3</sigma_c_true>
                <sigma_b_true>676.917</sigma_b_true>
                <sigma_uds>0</sigma_uds>
                <sigma_c>17240.7</sigma_c>
                <sigma_b>982.738</sigma_b>
                <sigma_uds_err>0</sigma_uds_err>
                <sigma_c_err>270.915</sigma_c_err>
                <sigma_b_err>36.0778</sigma_b_err>
        </bin>
</binning>

=== libov/zeus/db/results.highest.eta2.24.17.0405e06e07p.v02.true05e06e0607p.xml
<?xml version="1.0" encoding="UTF-8" standalone="no" ?><!DOCTYPE dataset SYSTEM "binning.dtd"><?xml-stylesheet type="text/xsl" href="binning.xsl"?><binning>
        <!-- eta jet -->
	<bin_group>
        <bin id="1">
                <subbin>
                        <variable>etajet</variable>
                        <low_edge>1.6</low_edge>
                        <up_edge>2.2</up_edge>
                </subbin>
                <k_uds>0.606687</k_uds>
                <k_c>1.98813</k_c>
                <k_b>1.74369</k_b>
                <k_uds_err>0.0381951</k_uds_err>
                <k_c_err>0.225154</k_c_err>
                <k_b_err>0.491358</k_b_err>
                <sigma_uds_true>0</sigma_uds_true>
                <sigma_c_true>1549.92</sigma_c_true>
                <sigma_b_true>93.8556</sigma_b_true>
                <sigma_uds>0</sigma_uds>
                <sigma_c>5135.73</sigma_c>
                <sigma_b>272.759</sigma_b>
                <sigma_uds_err>0</sigma_uds_err>
                <sigma_c_err>581.616</sigma_c_err>
                <sigma_b_err>76.8611</sigma_b_err>
        </bin>
        </bin_group>
</binning>
